export default TitlesText = {
  //obBoardingScreens
  titleOnBoardConect: 'Conecta con comercios',
  titleOnBoardCall: 'Llama o envía mensaje ',
  titleOnBoardReceive: 'Recibe tu pedido',
  titleWriteDirection: 'Escribe tu dirección',
  //login
  titleEmail: 'Correo electrónico',
  titlePassword: 'Contraseña',
  titleLoginScreen: 'Para continuar inicia sesión en tribo',
  titleNotAccount: '¿Aún no tienes cuenta?',
  titleRegisteHere: 'Registrate aquí',
  titleLoginError: 'El número telefónico no existe o la contraseña es incorrecta',
  //Profile
  titleProfileEditAccount: 'Editar mi cuenta',
  titleProfileName: 'Nombre Completo',
  titleProfileEmail: 'Correo Electrónico',
  titleProfileChangePassword: 'Cambiar contraseña',
  titleProfileEmaildIncorrect: 'Correo no válida',
  //welcomescreens
  titleSplashGreeting: '¡Hola!',
  titleSplashWelcome: 'Te damos la bienvenida a',
  titleStayHome: '#QuédateEnCasa',
  titleRegisterWithPhone: 'Regístrate con tu Teléfono Celular',
  titleBeginNow: 'Empieza ahora mismo',
  titleAnounceBussiness: '¿Quieres anunciar tu negocio?',
  //Store info
  titleStoreInfoAddress: 'Dirección:',
  titleStoreInfoPhone: 'Teléfono',
  //SideNavScreen
  titleSideNavRegister: 'Regístrate/Mi Cuenta',
  titleSideNavTerms: 'Términos y condiciones',
  titleSideNavFAQ: 'FAQ',
  titleSideNavPolicy: 'Políticas de Privacidad',
  //Registration screen
  titleRegistrationBienvenida: 'Te damos la Bienvenida',
  titleRegistrationRegistro: 'Registro',
  titleRegistrationCelular: 'Telêfono celular',
  titleRegistrationCorreo: 'Correo electrónico (opcional)',
  titleRegistrationNombreResponsble: 'Nombre del responsable del negocio',
  titleRegistrationNombreNegocio: 'Nombre de tu negocio',
  titleRegistrationComoSeLama:'Como se llama tu negocio?',
  titleRegistrationTelefonoNegocio:'Telefono de negocio',
  titleRegistrationDireccionNegocio: 'Direccion de tu negocio',
  titleRegistrationGiroNegocio: 'Giro de tu negocio',
  titleRegistrationVenta: '¿Qué vendes?',
  titleRegistrationFormasPago: '¿Qué formas de pago aceptas?',
  titleRegistrationDiasAbierto: '¿Qué dias ofreces servicio a domicilio?',
  titleRegistrationHorario: 'Horario de tu Negocio',
  //My account
  titlteMyAccountCuenta: 'Mi cuenta',
  titlteMyAccountTelefono: 'Teléfono celular:',
  titlteMyAccountCorreo: 'Correo electrónico:',
  titlteMyAccountResponsable: 'Responsable:',
  titlteMyAccountNegocio: 'Negocio:',
  titlteMyAccountDireccion: 'Dirección:',
  titlteMyAccountGiro: 'Giro:',
  titlteMyAccountVende: 'Vende:',
  titlteMyAccountFormaPago: 'Forma de Pago:',
  titlteMyAccountTipoEntrega: 'Tipo de entrega:',
  titlteMyAccountServicioDomicilio: 'Servicio a domicilio:',
  titlteMyAccountHorario: 'Horario',
  //FAQ
  titleFAQFunciona: '¿Cómo funciona la plataforma?',
  //Randoms
  titleRecomendations: 'Recomendaciones para el aislamiento preventivo',
  titleBussinessNotFound: 'Oops, parece que no hay nada aquí aún',
  //delete
  titleDeleteBusiness: 'Eliminar tu negocio',
  titleDeleteAccount: 'Eliminar tu cuenta',
  descriptionDeleteBussines: '¿Estas seguro que quieres eliminar tu negocio',
  descriptionDeleteAccount: '¿Estas seguro que quieres eliminar tu cuenta?',
  interrogationSimbol: '?',
};
